import Head from "next/head";
import Property from "../components/Property";
import { baseUrl, FetchData } from "../utilities/FetchData";

export default function Home({ propertiesForSale, propertiesForRent }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="text-gray-600 body-font">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-wrap -m-4">
            {propertiesForSale.map((property) => (
              <Property key={property.id} property={property} />
            ))}
          </div>
        </div>
      </section>
    </>
  );
}

export async function getStaticProps(context) {
  const propertyForSale = await FetchData(
    `${baseUrl}/properties/list?locationExternalIDs=5002&purpose=for-sale&hitsPerPage=6`
  );
  const propertyForRent = await FetchData(
    `${baseUrl}/properties/list?locationExternalIDs=5002&purpose=for-rent&hitsPerPage=6`
  );

  return {
    props: {
      propertiesForSale: propertyForSale?.hits,
      propertiesForRent: propertyForRent?.hits,
    },
  };
}
